In [1]:
import argparse
from sklearn.metrics import f1_score, accuracy_score
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from pytorch_pretrained_bert import BertAdam

from utils.helpers import get_data_loaders
from models import get_model
from utils.logger import create_logger
from utils.utils import *

import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="6"
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

import sys

In [4]:
import torch
import os

In [6]:
poster = torch.load(os.path.join("data_sets/proc/moviescope", 'img_indices2', '0.pt')).long()
poster =poster+4

In [22]:
poster = torch.cat([torch.ones(1).long(),poster,2*torch.ones(1).long()])

In [24]:
poster.size()

torch.Size([258])

In [20]:
torch.ones(1).long()

torch.Size([1])

In [2]:
args = argparse.Namespace(
        bert_model="bert-base-uncased",
        data_path="data_sets/proc/",
        task="moviescope",
        model="mmbt",
        batch_sz=8,
        task_type="multilabel",
        aug=0,
        drop_img_percent=0,
        max_seq_len=512,
        num_image_embeds=3,
        n_workers=8,
        poster="raw"
    )



In [3]:
train_loader, val_loader, test_loader = get_data_loaders(args)

In [4]:
from itertools import cycle

In [17]:
t=zip(train_loader,cycle(val_loader))

In [18]:
len(t)

TypeError: object of type 'zip' has no len()

In [13]:
set_seed(1)
for batch in tqdm(train_loader, total=len(train_loader)):
    txt, segment, mask, img, img_aug, tgt, img_id= batch
    print(img_id)

  0%|          | 2/432 [00:00<02:52,  2.49it/s]

[2643, 1520, 4301, 1656, 3720, 2238, 4719, 4268]
[3218, 3235, 3785, 3323, 2402, 1747, 2403, 825]
[4592, 1695, 2110, 1634, 2288, 3950, 1978, 1273]


  3%|▎         | 15/432 [00:01<00:23, 17.75it/s]

[1467, 5024, 2989, 245, 2283, 1458, 392, 1900]
[1050, 469, 482, 2171, 681, 1580, 3922, 3580]
[492, 2103, 1432, 1104, 1674, 1414, 4595, 805]
[2014, 1234, 4189, 4768, 1041, 4324, 1044, 840]
[4193, 3447, 3497, 1536, 4254, 3346, 2039, 3596]
[3062, 249, 4766, 478, 2168, 4485, 3154, 2779]
[1175, 1410, 3251, 4449, 4853, 3125, 159, 4380]
[1539, 2722, 1376, 151, 4895, 2874, 24, 1387]
[4526, 1007, 712, 4538, 2189, 429, 4978, 1981]
[874, 4057, 4584, 254, 3737, 1564, 1762, 1311]
[4938, 4778, 2849, 129, 2063, 4707, 3131, 3383]
[3830, 2119, 2394, 350, 1977, 3651, 2182, 982]
[1021, 557, 63, 2808, 1601, 653, 3525, 1360]
[2418, 4341, 162, 4561, 148, 3542, 4826, 1428]
[1149, 2035, 2401, 531, 4983, 3745, 714, 4667]
[1595, 2692, 727, 1186, 4031, 253, 1465, 747]
[1526, 3047, 969, 4356, 1972, 2870, 2025, 1764]
[1743, 2197, 2266, 1001, 4500, 4489, 4307, 645]
[2698, 2928, 4655, 3412, 713, 420, 1091, 3425]
[3495, 3809, 849, 3363, 4546, 2048, 2243, 1731]


  9%|▉         | 40/432 [00:01<00:07, 50.58it/s]

[573, 4453, 4617, 3610, 2651, 4576, 3382, 3801]
[4510, 329, 1717, 3016, 2680, 2625, 1959, 4391]
[4171, 2572, 534, 2588, 3430, 120, 1651, 2458]
[657, 321, 4074, 3848, 134, 3440, 1711, 2626]
[535, 3727, 16, 4759, 660, 175, 4613, 1036]
[4339, 367, 4754, 1491, 953, 4039, 1281, 1487]
[269, 1329, 4490, 3924, 1890, 4069, 1907, 2388]
[495, 73, 761, 4466, 3796, 4839, 4910, 3562]
[76, 4630, 1761, 3503, 2969, 2711, 899, 926]
[4468, 3325, 158, 118, 3093, 799, 2407, 186]
[3534, 2759, 797, 1159, 5039, 104, 2670, 2049]
[2857, 4140, 3345, 2804, 4333, 2215, 3110, 3159]
[4417, 568, 2148, 3909, 3585, 2159, 2504, 1968]
[1660, 1578, 4461, 4033, 56, 1439, 2769, 4400]
[1416, 174, 3613, 1971, 1436, 2204, 4351, 4728]
[2987, 2822, 4063, 1723, 1575, 3427, 4847, 1953]
[3657, 4525, 4569, 2975, 1735, 4156, 3511, 1008]
[3518, 4176, 1773, 4528, 2564, 3624, 2095, 3578]
[1352, 1529, 2191, 2509, 1176, 922, 1629, 4442]
[1237, 1877, 4691, 1381, 462, 2214, 1862, 1966]
[227, 3014, 957, 497, 131, 4565, 3938, 1105]
[2659, 505

 17%|█▋        | 72/432 [00:01<00:04, 84.96it/s]

[1334, 2955, 2287, 1614, 2127, 176, 3197, 2794]
[4246, 2092, 4878, 2218, 2553, 283, 683, 3395]
[4297, 3385, 744, 843, 328, 1463, 864, 662]
[2360, 2653, 1271, 1986, 3107, 3676, 3947, 4119]
[4115, 994, 2817, 3458, 1307, 2632, 1828, 907]
[2513, 853, 3628, 2456, 3143, 81, 4507, 3786]
[4709, 3153, 3919, 586, 3394, 25, 2780, 952]
[2505, 4620, 722, 4517, 1934, 1064, 3165, 365]
[3128, 3597, 1319, 2563, 2448, 1125, 290, 2170]
[4436, 2551, 3553, 966, 4098, 2545, 3022, 4706]
[1435, 1792, 846, 4881, 4976, 3424, 4686, 2851]
[2796, 4165, 1391, 4420, 810, 2934, 376, 2959]
[800, 3965, 3973, 4075, 3455, 3219, 460, 1018]
[3138, 1407, 2496, 4372, 4664, 1683, 4041, 2059]
[789, 550, 398, 4726, 2565, 1648, 1708, 980]
[3300, 2966, 2297, 3102, 1553, 4970, 4206, 4197]
[1304, 3223, 649, 1551, 4828, 4419, 3177, 2964]
[3378, 280, 693, 1751, 2234, 1082, 4300, 3743]
[4944, 4672, 4805, 2976, 2716, 2343, 1109, 4105]
[1819, 2832, 1727, 3728, 4337, 1382, 1100, 1027]
[1913, 3157, 4742, 2075, 3139, 3688, 4682, 3380]
[450

 24%|██▍       | 104/432 [00:02<00:03, 108.98it/s]

[4479, 3981, 2400, 4431, 2041, 3990, 2629, 2940]
[999, 4020, 1059, 204, 2264, 2581, 3353, 4704]
[2471, 2589, 1386, 4656, 1586, 2187, 3749, 3469]
[3625, 3563, 1623, 132, 2164, 3271, 869, 1675]
[2158, 4402, 1666, 1929, 3109, 1466, 4205, 2867]
[4773, 2667, 3048, 578, 52, 4841, 3729, 2657]
[1317, 4865, 1111, 279, 4724, 2661, 4905, 1804]
[3602, 1052, 3052, 3575, 4065, 3248, 3526, 1279]
[3485, 1556, 2357, 2677, 841, 3984, 96, 1637]
[428, 556, 4357, 3264, 4242, 2729, 2605, 4661]
[4397, 2052, 1232, 3824, 3869, 219, 2562, 228]
[1498, 1558, 4852, 1303, 4340, 2047, 2162, 2114]
[2293, 1846, 1802, 4271, 1179, 2718, 2521, 4681]
[1170, 4484, 3554, 1, 768, 1821, 4363, 368]
[4061, 2985, 138, 1060, 2353, 2093, 4280, 3314]
[4607, 3967, 83, 57, 400, 3415, 3474, 4083]
[1242, 2113, 1393, 4909, 1707, 1840, 3166, 2390]
[3937, 3080, 149, 3716, 3936, 3263, 1389, 444]
[3250, 1852, 1923, 4907, 736, 4084, 3833, 4138]
[170, 1605, 1960, 3636, 4804, 4152, 4913, 3901]
[2514, 2137, 427, 773, 3356, 201, 3205, 2278]
[709

 28%|██▊       | 120/432 [00:02<00:02, 105.67it/s]

[2475, 771, 4486, 4474, 1296, 596, 1985, 4593]
[3269, 1854, 112, 4487, 1855, 5018, 361, 2188]
[4840, 53, 2223, 647, 2764, 395, 107, 216]
[1881, 3311, 4711, 2927, 1079, 4597, 2038, 3789]
[2888, 1320, 6, 3400, 2032, 3594, 3507, 1662]
[1263, 2945, 4830, 905, 3763, 101, 3174, 4308]
[66, 1413, 3025, 1450, 3075, 2186, 2623, 574]
[1245, 1920, 182, 2494, 402, 721, 426, 4331]
[834, 4019, 4588, 3185, 2584, 2470, 3347, 4068]
[3502, 3225, 4971, 193, 781, 2939, 3468, 3361]
[1645, 4042, 4215, 499, 3558, 1049, 4362, 3939]
[4919, 3758, 3191, 3604, 1783, 3725, 894, 814]
[2440, 707, 2707, 3026, 2720, 3885, 21, 4749]
[140, 1504, 3288, 2855, 1496, 2583, 4352, 3443]
[2340, 64, 1607, 142, 2431, 207, 775, 1872]
[240, 4914, 3788, 3434, 1691, 500, 2968, 3987]
[795, 626, 2679, 3683, 3246, 4336, 3533, 2379]
[4531, 2222, 4381, 4889, 4272, 941, 1401, 1365]


 31%|███       | 132/432 [00:02<00:04, 66.88it/s] 

[2203, 1106, 3294, 2442, 405, 3309, 892, 168]
[979, 765, 1779, 2115, 4477, 4434, 2754, 91]
[3119, 82, 1787, 4618, 4245, 3925, 4806, 2592]
[396, 4006, 1594, 996, 1069, 948, 1238, 1661]
[2339, 1980, 4199, 3726, 3661, 1177, 2087, 4922]
[2372, 277, 3958, 2710, 3751, 1497, 4444, 4100]
[1815, 3319, 85, 705, 14, 4368, 354, 4194]
[553, 1206, 2877, 1812, 988, 945, 2486, 2630]
[3918, 2850, 4027, 916, 1301, 3392, 347, 3336]
[1604, 1253, 3045, 4516, 4629, 4184, 3097, 1213]
[1902, 527, 86, 3718, 4379, 733, 2342, 3386]
[1454, 2369, 3421, 2719, 4159, 1193, 3778, 4892]


 33%|███▎      | 142/432 [00:02<00:04, 64.89it/s]

[2751, 668, 4343, 3772, 1300, 3670, 1364, 185]
[2824, 4861, 3215, 2755, 2317, 70, 876, 3333]
[225, 4211, 2591, 3557, 440, 161, 1339, 1942]
[4646, 2160, 4670, 2021, 3376, 1346, 3441, 4851]
[4697, 2510, 3470, 2136, 2982, 2289, 1247, 690]
[1442, 4214, 1951, 3821, 4555, 937, 3267, 2290]
[1617, 3487, 3211, 458, 2140, 4802, 595, 3930]
[3538, 3423, 2797, 528, 4022, 3599, 3343, 4968]


 35%|███▍      | 151/432 [00:03<00:06, 44.29it/s]

[1408, 188, 896, 4807, 3028, 3972, 1394, 337]
[516, 1509, 1020, 1040, 3800, 964, 3243, 4869]
[203, 2355, 2919, 147, 2830, 1399, 1342, 4544]
[2815, 2819, 3517, 124, 98, 3500, 3998, 2309]


 38%|███▊      | 164/432 [00:03<00:05, 45.81it/s]

[2295, 2791, 2080, 3920, 1371, 4721, 3029, 1251]
[655, 5008, 3249, 1212, 3812, 382, 2847, 3422]
[1430, 682, 4054, 3834, 1426, 2434, 3074, 1185]
[4077, 4887, 4954, 3438, 589, 3679, 2868, 2184]
[3355, 4093, 3484, 210, 2699, 4866, 2898, 3975]
[1422, 2078, 4533, 1097, 1156, 2730, 740, 1618]
[3829, 198, 1883, 1158, 1998, 559, 4399, 1530]
[3584, 4264, 3354, 1725, 4817, 381, 1453, 1248]
[1636, 3955, 1133, 4276, 3724, 698, 2428, 1188]
[308, 577, 4225, 4014, 3876, 1593, 422, 0]
[4779, 1665, 111, 4660, 3204, 3227, 1192, 217]
[4739, 1411, 2712, 4220, 1848, 3884, 1703, 2452]
[459, 1988, 4888, 27, 4141, 1866, 1720, 418]
[3327, 1063, 1479, 2273, 4396, 3637, 322, 3489]
[4775, 1441, 1892, 1475, 612, 2328, 1563, 4601]
[3482, 1671, 2663, 1686, 2897, 1758, 3330, 1482]


 39%|███▉      | 170/432 [00:03<00:07, 35.32it/s]

[2782, 3806, 421, 252, 1166, 3522, 1914, 3827]
[3387, 3761, 456, 97, 2019, 4605, 3712, 621]
[2068, 3149, 2004, 2036, 1486, 1278, 194, 936]
[5025, 2150, 3752, 2930, 4223, 3409, 2896, 2501]
[3368, 4096, 4118, 4668, 2082, 4542, 3849, 473]
[3715, 3460, 1540, 2118, 4126, 4497, 4269, 3980]
[2120, 2196, 1452, 4735, 3844, 1313, 2858, 652]
[3002, 3173, 3167, 2275, 439, 433, 4977, 3050]


 43%|████▎     | 186/432 [00:04<00:06, 38.21it/s]

[4208, 4993, 1081, 1216, 5009, 4315, 3461, 3013]
[4233, 1633, 1469, 1004, 4793, 1561, 732, 34]
[4190, 1046, 2631, 102, 3496, 345, 4743, 1705]
[3201, 1597, 4594, 4694, 4201, 3334, 273, 1973]
[4187, 1910, 2689, 119, 5020, 2642, 2123, 1144]
[472, 4395, 3680, 4378, 1053, 2662, 2130, 3053]
[3790, 4249, 3160, 3290, 1369, 4551, 554, 624]
[4239, 2635, 344, 599, 2986, 4167, 858, 674]
[640, 4241, 2466, 4932, 646, 1355, 2604, 4602]
[2245, 184, 2957, 3043, 4374, 4234, 4558, 766]
[2624, 4295, 4173, 223, 1183, 520, 4177, 4186]
[4495, 4102, 4317, 3735, 4951, 2208, 541, 2889]
[1903, 2190, 3555, 3196, 2406, 3694, 1215, 835]
[4925, 1610, 1013, 1632, 2348, 2749, 2081, 1250]
[153, 2721, 3805, 2153, 2050, 4314, 609, 3864]
[1567, 2371, 887, 3687, 2074, 3129, 3841, 3701]


 49%|████▊     | 210/432 [00:04<00:03, 64.12it/s]

[1818, 37, 2756, 4153, 2831, 2419, 4258, 504]
[3590, 105, 4785, 471, 3253, 5035, 4679, 2901]
[2612, 3940, 1598, 2929, 2903, 4038, 603, 4409]
[4619, 816, 2905, 3509, 3444, 1957, 2389, 2377]
[1823, 1102, 2807, 1493, 1233, 4328, 1108, 4327]
[2022, 231, 610, 1944, 2763, 4683, 3611, 2746]
[2144, 490, 1543, 856, 1078, 670, 1642, 3703]
[1833, 962, 4553, 903, 4973, 4761, 4819, 2053]
[1055, 4162, 2594, 3825, 2839, 4248, 1941, 5022]
[3268, 677, 244, 3700, 1478, 4000, 635, 3117]
[4178, 3644, 631, 4432, 3616, 2006, 2593, 532]
[2, 2425, 3822, 1611, 1354, 3471, 4053, 4261]
[1420, 774, 42, 3410, 3552, 141, 2894, 3570]
[271, 3954, 3750, 2067, 2212, 2084, 3655, 4030]
[2374, 3439, 3072, 1995, 26, 2003, 1340, 990]
[353, 3690, 333, 3379, 4422, 4994, 4011, 3588]
[2239, 3172, 2798, 4810, 106, 2200, 973, 4137]
[3779, 3603, 1757, 583, 778, 1235, 1107, 3873]
[4112, 1367, 2155, 2559, 310, 1706, 2843, 4342]
[4398, 2133, 2814, 2524, 3771, 566, 2405, 4860]
[3916, 2179, 3240, 2726, 3867, 4128, 762, 3541]
[2688, 197

 55%|█████▍    | 236/432 [00:04<00:02, 85.82it/s]

[1640, 854, 3190, 291, 1649, 1500, 706, 163]
[4900, 1058, 262, 506, 1876, 4127, 4634, 156]
[4103, 1083, 3704, 4789, 1061, 484, 2498, 750]
[3431, 2547, 1506, 3171, 1544, 2788, 3685, 3640]
[2219, 724, 3032, 2671, 808, 4425, 2427, 3322]
[5011, 560, 92, 1570, 2180, 752, 2895, 1969]
[1211, 2276, 3001, 2381, 976, 4232, 1658, 981]
[3238, 1572, 309, 1730, 4632, 525, 4257, 2787]
[2116, 1025, 3175, 384, 593, 2856, 4783, 3132]
[4237, 2875, 4243, 4392, 2709, 1260, 2230, 394]
[3851, 3231, 2099, 2061, 3136, 1781, 2294, 2311]
[4150, 4085, 4769, 956, 3706, 4956, 704, 2375]
[3514, 4600, 2299, 1207, 1628, 2477, 334, 4614]
[189, 3513, 4095, 1559, 4413, 2734, 1252, 1072]
[1835, 4961, 1370, 1746, 1831, 242, 3946, 4012]
[323, 512, 1200, 2149, 3005, 2906, 3060, 2138]
[3581, 3593, 2163, 4915, 2483, 2349, 288, 2508]
[3127, 2469, 3738, 1669, 4906, 45, 3011, 2154]
[2777, 2364, 3609, 2257, 3783, 181, 3318, 2639]
[23, 1554, 59, 1210, 1348, 738, 1228, 67]
[920, 4871, 1383, 2493, 3405, 4912, 3693, 3895]
[4729, 4388,

 58%|█████▊    | 250/432 [00:04<00:02, 78.86it/s]

[58, 3428, 2752, 1867, 2803, 4669, 4406, 3254]
[4844, 2654, 4023, 3798, 399, 4943, 5015, 1906]
[3187, 3479, 2029, 1227, 4760, 4514, 967, 2606]
[3273, 617, 2392, 1086, 457, 614, 2892, 4135]
[1134, 927, 851, 521, 2105, 4680, 1983, 3686]
[4814, 474, 1347, 286, 696, 759, 3217, 4575]
[2096, 3665, 3537, 4122, 558, 4627, 4643, 3084]


 60%|█████▉    | 259/432 [00:05<00:04, 37.29it/s]

[4291, 989, 1696, 4687, 1160, 2229, 2543, 620]
[2556, 1581, 391, 3058, 1534, 1150, 3176, 2811]
[4136, 3886, 4148, 3200, 3926, 1918, 2071, 2960]
[4279, 4421, 2658, 4685, 884, 4207, 889, 4192]
[2447, 1654, 2217, 3454, 917, 2378, 1542, 4953]
[4079, 3843, 3094, 767, 549, 2503, 44, 3398]
[2962, 335, 3564, 1312, 3358, 3654, 4788, 4131]
[832, 2142, 314, 4930, 1853, 3855, 2064, 2202]


 62%|██████▏   | 266/432 [00:05<00:04, 34.42it/s]

[1084, 2727, 977, 3433, 2270, 2531, 1650, 3226]
[1933, 601, 452, 4370, 3073, 3501, 4838, 260]
[1778, 3036, 2733, 1679, 2312, 4540, 2055, 3756]
[539, 820, 2988, 4358, 1938, 232, 257, 5037]
[1993, 995, 2365, 970, 2216, 4473, 4410, 3012]
[274, 3079, 1955, 229, 1246, 2306, 3164, 1065]
[1832, 1789, 4401, 2552, 1794, 4429, 1451, 4737]
[2122, 3202, 2516, 4586, 3505, 2860, 2641, 485]


 64%|██████▍   | 277/432 [00:06<00:05, 30.63it/s]

[1615, 4854, 1341, 4950, 2274, 3366, 199, 33]
[4055, 423, 2676, 1327, 4564, 616, 2595, 3618]
[2286, 697, 3820, 3063, 4456, 739, 2145, 3799]
[1077, 2805, 1756, 746, 4404, 4921, 4537, 303]
[455, 285, 2747, 190, 2776, 882, 4441, 1765]
[4545, 4321, 415, 4650, 2176, 1626, 3734, 2899]
[4710, 2033, 4518, 5026, 4236, 2334, 2313, 786]
[1501, 3539, 3932, 3104, 3560, 2318, 3888, 1668]


 65%|██████▌   | 282/432 [00:06<00:04, 31.95it/s]

[3483, 4412, 3963, 139, 4981, 4182, 2482, 2795]
[3999, 3696, 1115, 3853, 1608, 1873, 1397, 3120]
[3266, 5000, 261, 327, 2741, 4716, 4224, 658]
[54, 3529, 2579, 4568, 2715, 2454, 2015, 4008]


 69%|██████▉   | 299/432 [00:06<00:03, 33.92it/s]

[18, 1268, 230, 2044, 863, 3130, 3960, 1715]
[803, 695, 1073, 4791, 1345, 2352, 3887, 1911]
[3622, 666, 4305, 4616, 4064, 2463, 857, 3587]
[1258, 3802, 3293, 2344, 2474, 1162, 1641, 3607]
[200, 4967, 4604, 2404, 4734, 1089, 1003, 3051]
[2007, 2307, 2774, 2880, 3242, 4366, 1456, 3396]
[3592, 3907, 639, 3546, 357, 1531, 266, 1030]
[3835, 2421, 2413, 3241, 630, 3198, 2301, 46]
[3516, 316, 4599, 3556, 2876, 3007, 544, 3341]
[1639, 1829, 4916, 4966, 1368, 2611, 4375, 2065]
[4917, 3095, 4457, 177, 1384, 3647, 575, 4060]
[3544, 1547, 3872, 1624, 3548, 3429, 4013, 1421]
[4508, 986, 4872, 4822, 4158, 3044, 2083, 89]
[923, 30, 1573, 442, 1961, 2457, 2057, 2285]
[1128, 4216, 5017, 625, 4626, 414, 3274, 3638]
[2499, 2970, 944, 1087, 3747, 362, 925, 4557]
[4809, 2484, 2242, 3156, 3945, 238, 2277, 2117]
[3649, 4929, 3000, 341, 2573, 299, 3277, 4080]
[2655, 3179, 4864, 2784, 4151, 2433, 3359, 2549]
[2841, 4304, 2500, 87, 1537, 3620, 1067, 2781]
[3328, 4615, 2967, 4212, 39, 3754, 726, 1014]
[477, 4877

 75%|███████▌  | 324/432 [00:07<00:01, 57.78it/s]

[2398, 2267, 1673, 2748, 3699, 304, 3897, 2785]
[2690, 4139, 3589, 591, 434, 1029, 848, 1433]
[4581, 1684, 1791, 3566, 3186, 2429, 684, 3090]
[3883, 2028, 3113, 4868, 1956, 798, 2922, 3913]
[498, 4596, 358, 137, 1138, 2018, 4428, 699]
[144, 764, 4843, 2031, 1241, 1987, 3803, 5041]
[2517, 4458, 2646, 100, 3498, 3477, 4050, 3124]
[1038, 4267, 3629, 1798, 3009, 954, 3260, 1926]
[2920, 5029, 2771, 1541, 987, 2980, 489, 2321]
[61, 4354, 4823, 2681, 2373, 4104, 548, 3466]
[3375, 19, 281, 2459, 2435, 4465, 3306, 4896]
[1874, 2865, 3283, 4756, 2816, 2438, 1434, 1871]
[720, 4652, 3582, 3391, 2950, 3066, 2723, 3948]
[3668, 2198, 1793, 224, 4573, 2010, 2530, 4792]
[2437, 4332, 5012, 1306, 2908, 2599, 1285, 4283]
[2247, 845, 1147, 929, 364, 1043, 1644, 2393]
[3793, 4770, 3068, 2772, 493, 1990, 1510, 2011]
[2577, 633, 4511, 38, 2152, 3689, 975, 1349]
[685, 4622, 3722, 1161, 3106, 3181, 3493, 4790]
[1224, 4482, 3, 1797, 2704, 3256, 1010, 1071]
[2246, 2600, 1326, 4750, 4952, 1775, 4107, 2076]
[1879, 

 77%|███████▋  | 333/432 [00:07<00:02, 41.05it/s]

[88, 40, 1226, 4005, 4671, 4986, 3435, 619]
[2151, 3881, 1663, 1997, 2043, 2233, 3081, 4312]
[3510, 1606, 606, 2462, 2070, 1546, 43, 891]
[213, 4658, 636, 2232, 3126, 237, 1803, 4580]
[2335, 3178, 2773, 5031, 3161, 1878, 4606, 928]
[1528, 2893, 2220, 2207, 4259, 2060, 3147, 1476]
[2900, 372, 2089, 2535, 3399, 1142, 3861, 4154]
[4322, 5005, 855, 275, 1337, 3917, 1270, 2848]


 79%|███████▊  | 340/432 [00:07<00:02, 33.69it/s]

[1113, 1638, 1328, 3133, 2806, 3389, 4097, 3608]
[1195, 3276, 2129, 4989, 1770, 195, 2546, 2175]
[1817, 4505, 1085, 570, 4418, 4226, 3108, 1243]
[2702, 2933, 4244, 3419, 1425, 4727, 1689, 1984]
[1928, 2205, 4690, 2453, 160, 5036, 2644, 1054]
[4856, 4231, 4539, 4445, 780, 4345, 3056, 3279]
[3236, 78, 4493, 3605, 1136, 2536, 1851, 3247]
[167, 2173, 1470, 1220, 3579, 2652, 3348, 4985]


 81%|████████  | 348/432 [00:08<00:02, 29.44it/s]

[2532, 1565, 838, 1169, 1976, 3370, 2574, 4530]
[411, 4347, 3475, 2320, 3140, 974, 4862, 1701]
[3814, 4740, 2254, 3078, 295, 1198, 2476, 3985]
[3163, 4394, 1753, 3180, 3773, 20, 412, 4058]
[2863, 3882, 2801, 3572, 1114, 4405, 3170, 3360]
[3600, 3114, 1157, 1515, 1967, 5040, 623, 3929]
[579, 2953, 734, 1023, 2566, 3614, 2576, 4319]
[2537, 2972, 2992, 4534, 3059, 2766, 3442, 2820]


 82%|████████▏ | 356/432 [00:08<00:02, 27.37it/s]

[3261, 75, 1137, 1291, 4918, 1790, 2107, 2249]
[2424, 222, 3064, 2615, 2527, 4114, 1132, 1733]
[3344, 3417, 1139, 356, 1148, 1415, 265, 5027]
[4777, 4603, 1026, 888, 1181, 1904, 1424, 3490]
[1163, 839, 247, 1299, 3041, 1989, 1096, 1388]
[4290, 3436, 3076, 2725, 1259, 3144, 745, 1811]
[2327, 753, 801, 1677, 2316, 1936, 708, 379]
[1739, 2009, 2027, 4902, 196, 3213, 895, 215]


 84%|████████▍ | 364/432 [00:08<00:02, 26.97it/s]

[3145, 1196, 4875, 4302, 847, 2347, 3863, 4648]
[3902, 2226, 2194, 3935, 1031, 3549, 3842, 1545]
[519, 641, 1915, 3023, 1692, 4446, 1600, 2984]
[3183, 3838, 3299, 1962, 2443, 2947, 1716, 3373]
[3337, 1946, 2918, 305, 2206, 4772, 4893, 4506]
[1374, 2882, 4478, 2185, 3532, 4124, 150, 2225]


 89%|████████▉ | 386/432 [00:09<00:01, 40.91it/s]

[169, 509, 2135, 4294, 3969, 5032, 2324, 1190]
[136, 4621, 1519, 751, 146, 679, 1931, 770]
[3781, 1801, 4559, 785, 938, 2550, 661, 2346]
[824, 1229, 3659, 3414, 3033, 1886, 4640, 2792]
[2696, 4639, 1964, 3894, 1901, 1380, 4089, 2487]
[2201, 1860, 1318, 2887, 4185, 3101, 1474, 1122]
[2330, 1722, 326, 1011, 3508, 3034, 2132, 47]
[3372, 4090, 438, 1269, 3571, 4649, 1613, 250]
[4464, 671, 4467, 4712, 1330, 1019, 2181, 2825]
[2745, 1800, 324, 3753, 1518, 4325, 449, 1511]
[359, 912, 373, 836, 2345, 2570, 1321, 2077]
[3862, 1255, 809, 2329, 567, 1287, 2977, 1592]
[1958, 3408, 4266, 2326, 1406, 1180, 971, 1865]
[13, 4651, 2760, 4751, 468, 4624, 3627, 2616]
[3437, 1917, 3656, 1239, 3504, 1473, 2944, 569]
[4228, 4879, 1405, 3702, 5013, 2910, 166, 817]
[604, 4365, 2762, 115, 1468, 4292, 4901, 2473]
[3112, 4313, 3811, 488, 1924, 425, 2633, 446]
[3692, 538, 4329, 4344, 4824, 4659, 470, 3991]
[2410, 4891, 687, 2449, 3865, 3995, 1589, 2861]
[487, 3595, 2990, 4931, 2489, 4535, 4974, 437]
[1709, 3896, 

 97%|█████████▋| 417/432 [00:09<00:00, 70.48it/s]

[4894, 2835, 3658, 1095, 3970, 5, 3340, 3193]
[776, 4045, 205, 239, 15, 3956, 2091, 1694]
[4021, 1514, 3524, 2569, 1524, 155, 2520, 3381]
[4087, 296, 2523, 3499, 2983, 5023, 1123, 2166]
[1702, 4110, 1975, 1939, 1222, 1116, 2802, 3652]
[3155, 4390, 2902, 1732, 3857, 822, 2338, 2165]
[3017, 743, 648, 4674, 1028, 2488, 2495, 2854]
[236, 4198, 909, 2758, 3949, 5010, 2952, 4644]
[700, 248, 572, 1117, 4713, 2812, 1099, 3158]
[312, 4520, 3086, 2292, 4235, 2799, 667, 403]
[1488, 479, 2973, 3397, 4999, 3150, 4820, 3307]
[1359, 827, 1112, 2628, 719, 1728, 1257, 760]
[1495, 2757, 3162, 2761, 503, 622, 4472, 3096]
[4111, 2298, 904, 972, 1513, 2310, 2948, 1768]
[1145, 1838, 1954, 152, 3832, 4438, 1667, 2750]
[2668, 1533, 4747, 3272, 4831, 3711, 508, 3819]
[3019, 4688, 602, 1719, 1494, 3736, 3324, 1631]
[448, 4678, 3740, 3280, 1571, 3598, 4942, 675]
[2097, 3905, 701, 4801, 4926, 3245, 1390, 4513]
[4071, 3520, 4958, 4377, 4353, 4857, 3281, 1550]


 99%|█████████▉| 427/432 [00:09<00:00, 60.53it/s]

[2872, 3994, 62, 2323, 1754, 978, 644, 4443]
[1836, 2260, 125, 4469, 3362, 823, 180, 2485]
[833, 4172, 117, 4403, 4222, 1375, 1898, 3941]
[590, 2936, 1844, 3134, 94, 2818, 2341, 2999]
[1653, 4512, 1748, 2056, 4491, 410, 2961, 4886]
[3121, 49, 1088, 4799, 2085, 515, 1742, 2409]
[1822, 3221, 4488, 3450, 4066, 4180, 3664, 2890]


100%|██████████| 432/432 [00:10<00:00, 42.17it/s]

[4897, 4980, 2963, 1141, 1577, 4475, 1202, 51]
[643, 494, 419, 4647, 3714, 2937, 3952, 3828]
[366, 1254, 4144, 1891, 3645, 4414, 183, 3527]
[4870, 4361, 4589, 1562, 850, 1172, 2607, 352]
[1745]


In [23]:
set_seed(1)
for batch in tqdm(zip(train_loader,train_loader), total=len(train_loader)):
    txt, segment, mask, img, img_aug, tgt, img_id= batch[1]
    txt2, segment2, mask2, img2, img_aug2, tgt2, img_id2= batch[0]
    print(np.array(img_id)-np.array(img_id2))

  3%|▎         | 14/432 [00:00<00:06, 63.75it/s]

[  553 -1072 -3658  2116   724   328 -2173  -784]
[  849  1395 -3090  -572   712 -1208 -1259  3592]
[-3480  -606  -988  3244 -2034 -2104  -633   316]
[-1346 -2604 -1333  3321  1430  3035   629 -1509]
[ 3018  3136  3255 -1803   598  1603 -1769 -1748]
[ 4135  2037  1929  -167  3233  2986 -4169  2907]
[ -928  1626 -2126 -4454  -856 -3083  -993  -334]
[-1294 -3003   106  -510 -3518 -2659   628 -3063]
[-2896  2582  -415  2336 -1175 -1862  1292 -2746]
[ 3059  1596  1115 -1175 -2902   971  1518   -15]
[1122 1417   -8 3907 -923  406 2161 -570]
[  485  -144  3447 -2319  2189  2718  -281 -1732]
[-728  341 -778 3248  982 1593 1132 1445]
[-4283 -3170   137  1472  1770 -1773   766 -1390]
[  704  -274   286  1323 -1544  -775  2210  3424]
[-407 -277 3529  969 2512 3795  852 2256]
[  759  -787  1138 -4486   888  1039 -4344  1600]
[ 1221  1879  1442   -67  -386 -2248  -657 -4310]
[-1091 -2026  2217   -78   966  4575 -1329  3415]
[ 2263    -4  2284 -1250  2486  1111  1172  2715]
[  215   180   798  -380

 10%|▉         | 42/432 [00:00<00:04, 97.48it/s]

[-4440   307  1275  1865   799 -1082   671 -2989]
[   92 -1313  4001 -1134 -2366  2315  1393 -1072]
[ 3907  2925 -1060   497  4509 -1090  3094  2227]
[  327 -2388   659  -685  2524  3653  -581  1063]
[-1647   686  -540  2305  1152 -3272  3400  2669]
[ 3395   668 -1955 -1127  2978 -3733  2269   321]
[ 4058  2005   557 -1611 -1508 -4724 -3540 -1105]
[ 3756   355 -1389  -183  1626  -579   798  2521]
[-3042  -325  1603  4759  1698  -190 -2206  4131]
[-1505  2106   673  3643 -2285  2853  -586  2811]
[   63  -540 -2771   294   696 -1083 -2751 -3071]
[-1990  2831   -99 -3256    76 -1197  -856   470]
[  240  -764 -3096 -1032  3319  1154 -2423 -3687]
[  625  4757 -3290   830   224   390 -2373  -203]
[-2383 -2815  -475  1915  -141 -2220 -2185 -1152]
[-1497  -633 -3170  1763   403 -3834  1402  3393]
[-2035 -3251  1186    92  -630  -260 -1731 -1089]
[ -191  2459  -594  -435 -1170  2063  1419 -3793]
[ -843  2213 -3636  2569  -188  2442  -777  2462]
[ 1588 -1840  2006  4043  1395 -3683 -3322    10]


 16%|█▌        | 70/432 [00:00<00:03, 111.48it/s]

[ 2046  -502  1915   687  3181 -1860  -846 -1778]
[ 4105  3481  1181    13 -4187  1615  -376   236]
[-2036 -2807  2136 -3733  3032   799   602 -2094]
[-2210 -1999  1132  2153  -422   286 -1774  -438]
[ 3521  2781  1585  -398 -2555   734  -199 -1776]
[ 3525 -1051  1534  1795   333 -1597 -1040  3316]
[ 2394   125   497  1564  2453  3578   405 -2749]
[ -852 -1407 -1361   954   464  1196  2618   139]
[-1720 -1545  1685  1123  2298  2647   904  -178]
[ 2350 -1428  1138  2504  1786 -2095 -2982  -171]
[-1049  1704 -2797 -2089  3047  -356  1986  1851]
[  376  3689 -2885  -262 -2029  4004 -4453 -2053]
[-3352 -2862 -2770  1959 -3262   150   358  -887]
[ 2221  -838  2841 -4043    18  2409 -2686  1109]
[-1798 -3271  1212 -1413  1116  -299   -24  1819]
[-1728  2261 -3267  -798 -2406  -248 -1827 -1697]
[  598 -1115  2730  -703 -3122 -1050  -545 -2837]
[ 1059 -2873   529 -4197  2077 -1436  3849  -712]
[ 2671 -1504 -1056 -2297   620 -2006   454  1210]
[ -396  1140  -493 -2766 -2352   585  -939   765]


 22%|██▏       | 97/432 [00:00<00:02, 116.89it/s]

[ -601  4693  3561   -21 -1566  -307 -1758 -2814]
[-4075 -2432  -145 -1169  1259 -1305  3766   705]
[ 1768 -2094  2114 -2009 -4195   622   579  3163]
[ -662  1165 -4307  -404  1274   639  -272   458]
[ 2349  2056 -1675 -3148   255  -978  3991 -1321]
[-1598 -3874  -869  1211  2840  -335 -2136 -1667]
[-1296  -267  -478 -4725   405  1814  -289 -1482]
[ 3720     1  3775  1030  2482 -4260  2718 -1680]
[  849  1842  -528  -733  1269 -1579  2382  4008]
[1327 2641 -419 -557 -245 1524 -647 2433]
[ 1256  1072   196  3107 -2505  -173   237 -2433]
[ 1942  1035   198  -363 -2687 -1775 -1182   992]
[  446  2853  2279  -649  3196 -2003  -490 -1910]
[-1211  -736  -609  2213   637 -2545  1717   851]
[  438 -1632   288 -2417 -1410 -3195  2271 -1420]
[ 3898 -2452  -103  3743  1115  1563 -1096 -4383]
[-1077  -187   736  -747  1595 -1772 -1689    63]
[-1471   421  -433  1265  2523   879   -93  1308]
[-2039 -2466  2539 -1385  1923  2629 -1737  2025]
[-3258 -1315  1961  1604  4779  -829 -1936   124]
[ 1982 -

 25%|██▌       | 109/432 [00:01<00:03, 102.15it/s]

[-2567 -2013  2519  -751   748  2769 -3830 -1665]
[ -395  -280   578   329  4501 -2332 -3305 -3142]
[ 3004  2914 -1060 -2838   703 -1692  1728 -1056]
[-3459   312    37 -1976   703 -1612  1094  3710]
[  761  2790   -63 -2239  4176  -624  -395 -3878]
[ 4756  -394  3058 -2480 -1246  -940  -404 -1905]
[  130  -545  3830  1428  -434    70 -2968   333]
[ 4145  -264 -2206 -1544   -14 -1738   194  2065]
[  203 -1007 -2025 -3470    32 -2152 -2206   538]
[-1681  1766   247   145 -1605  2271   102 -4058]
[ 1276  2427  1749  -976  2776  2531  -312 -3302]
[  696  -634 -3667  -730  1509   193  -658 -1195]
[ -928  -607   361 -3679   597 -1878  1984  -336]
[-2784  2499 -2078  3187 -1371  2634   137  3971]
[-1043 -2320 -3999  1053  1520 -2274   924 -3333]
[ 1454  2089  3150   792   -14 -1391  -945  1019]
[ 3701  -154 -4501  3103  -546  2545 -1692 -1512]


 32%|███▏      | 139/432 [00:01<00:02, 113.45it/s]

[ 3683 -1097   710  2662   854   395  -643  2275]
[2152 -591  378  442 -340 2123 2212 -722]
[ 2155 -2748 -1696  -807  -599   100  1072 -2351]
[-1774  1598 -4072   376  3121  -824 -2480 -2739]
[ 3181   481 -1969  1852 -3455   -69    81  -970]
[ -362 -2788 -1497   194  1797 -3388  -506  3818]
[ 2165  3799  2010 -2870   447 -3756  4669  -232]
[ 1622  3225   181  -565  3198  1061  -222 -1060]
[-1482   457  1275  2560   148  2769  1820  -566]
[ 3692  -483  1201  1396  2306  3569 -1756   404]
[ -269  3416 -2464 -3393   448   161  -144 -2044]
[-3733   490  -559 -1984 -1103   371  2806   454]
[ -750  2888   305  2286   452 -3005  3862   974]
[ 4047  3497  -632  -977 -1399 -1342  1176  1384]
[ 1120  2724  3163 -4159  -361 -1262 -4207  -727]
[ 1490 -2396   377   439  -450  1527  1374   649]
[  834 -1328 -2632 -1503 -3153  1576 -1003  -835]
[-2168  3131   610   908 -3400  1277 -1844  -724]
[   47 -1540  1022  1372  2786 -4171  4415 -2853]
[ 4233 -1055 -2168  -376   955  3298  1001 -1519]
[ -946  

 36%|███▌      | 155/432 [00:01<00:02, 118.80it/s]

[-1655 -2594  -408   598  -411  3648  1541 -2830]
[ 3108 -4155 -1411 -2244  2798   812  1526 -1713]
[ -272  1895 -2431  2678 -1970  2787  -296 -1000]
[-4027  -380 -3296  -436  1909  2269  1141  2710]
[  884 -2814  -712  1084  -284   130   766  2722]
[   98 -2783 -2549  1785  1335 -3896  2682 -2872]
[-2616 -1623  -568  1885 -3933 -1040   238 -4726]
[ 2449   971  1780 -2291  -160 -2516   838   964]
[ 1012  3004  3040  -147 -3792  3900  -670 -3164]
[ 2239  -737   285  3554   972 -1384   -35 -1085]
[  196   759   634  4273  4371 -3414 -2275 -1455]
[ -362  1782  2626  -437  -311 -1326  1640    10]
[  -83   -48 -2718   577 -1938   613   279   347]
[ 2763   -89  -541   887   601  -821 -1004  3479]
[  789 -4262 -3773 -1657  2646   492 -2251 -1742]
[ -299 -2057 -3265  2274  2025 -4034   109  -503]
[ -593  1018 -3057  3061   909 -1019  2953   537]
[-1958  3146  -996  3810  2911  1270  -852   658]
[-1177  -992  -352   882 -2734  2740  1570   961]
[  999 -1864 -1074  -780 -1906  -320 -1691  1042]


 43%|████▎     | 184/432 [00:01<00:02, 121.08it/s]

[-2621  1206  2095  3423  2175 -4518 -3417  2973]
[-1869 -2874  1246   273  -588   478  1275  -101]
[-1807  2784 -2189  -207 -2268 -2438   208  2066]
[  286 -2390 -3695 -4574 -1092 -1381 -3611   523]
[-2079 -2343   969  2150 -3418 -2064  -364   172]
[ 2199   654  -903 -2205 -3814  3542  -751   -85]
[  234 -2119  -365  2745  3206   907 -4905  1697]
[ -170 -3857  2501  -235 -4265  -399  -622 -2213]
[-2450  -699   454  1528 -2670  -705   531  3076]
[-1734   770 -2529  3145  1458  3009 -2269  1709]
[  900   467 -1504 -1975 -4007 -1740  3266 -1536]
[-1843  -781  1603  1060 -1085  2244 -1980  1078]
[ -374 -1831 -2547 -2832  2378 -1067   274  1247]
[  514  -679 -2500 -2048    99  -447  1883  2439]
[-3956  1774  -271  2767 -2637 -1802  -342  -450]
[ 3911 -4199  -611 -4604   918   313  1595 -1084]
[ 2438  1347 -1505 -1097 -2774 -3736  -591  -279]
[  -35  -625 -4061  4790  2807  3055 -2274  -167]
[  437 -2641   209  -235 -2427  1765  4114   380]


 48%|████▊     | 209/432 [00:01<00:02, 103.00it/s]

[  179 -2126 -2531 -1582 -1992 -1873  2357  4083]
[-3226  1015   237   566   785 -2561  2269  2525]
[ 1579  -388 -3216  1940 -1579 -2541  4015   473]
[  -30   913  2406 -2477   243  1200 -3645     1]
[  250   931   -60 -1811  -485 -1184 -2562   545]
[-1692  3122 -1404   592  1181 -3071  -322  -850]
[-1787 -1789  1739  -396   801  -697  2003 -2081]
[-1134  2338  1829  -956  1121  -818  1236 -1318]
[ -428   567 -2250   -65   786 -4125  -856 -4278]
[  750  4373   727   -78 -1490 -1853 -2294 -1576]
[ -723  2169   160  2264  -626  4107  2337 -2240]
[ 2855  4078 -3599   184 -4400 -3070 -1655  -773]
[  291 -3428 -2291 -2142    80 -2162 -1543 -4218]
[   77  1617  2669 -1783  2774 -3693  1915   714]
[-2367 -1263  3024   -92 -3151  1520 -2546    19]
[ 2586   340 -3215  2365  -360 -2618   863 -2275]
[ -739  2703  3246 -3293  -339  2560  -409 -2276]
[  983   -81 -3632 -1701 -1110  -260    60 -1474]
[  -26 -1034   160   545  2343 -1253  -792  1735]
[ 4027   424  1624 -2335 -3533 -4294  -811   709]


 54%|█████▍    | 234/432 [00:02<00:01, 113.25it/s]

[  123  1714   123 -2379  1035   665  -718 -1037]
[-2349  4462  -194 -3154  1408  -331 -2151  3470]
[ 4117 -2774  4214  4038  4228   280  2866 -2314]
[ 3542  -495  -421  1994   700 -1074   792  -609]
[ 1146 -3891  -167   940  1465  1326 -2182  2726]
[-1459  2844 -1909  2219  1005  2942  2423  4607]
[-3823  3360  1375  2215   844   692 -2030  1592]
[-1148  3183 -3646 -1248  -414   411 -1470  3491]
[ 1255   740  1033 -2167  -211 -1282  1267  -987]
[ 1492  3162 -2331  1681  3297  -654 -2195   367]
[-3783  4311  4942  1475  2087  1876  -492  -993]
[ -983  -737  1816  -659  -551 -1804   193  -731]
[ -909   259  4111 -1465 -3912    -5  -412  1158]
[ -672  -536 -2791  4572  1459 -1155 -2775   -86]
[-2094 -1295 -3822 -2413 -2108  3340  1894  1473]
[ -117  -541  -588  1193 -2220    33  2576   995]
[-3391 -2714 -4687   347    89  -960  4274  1376]
[  780 -3874  1612  1690   875 -1194  2826   385]
[  999 -2416 -3975 -1419 -1789    61  1353  -623]
[ 2791 -3017  2262  -530  3075  2350 -1622 -3518]


 57%|█████▋    | 247/432 [00:02<00:01, 97.90it/s] 

[ -277 -1775  3349 -2419   837  -257  2512  1506]
[-2110  3022  2560  1627 -1296  -970   350  -951]
[ 2345 -2586   980 -3870  -438 -2854  2050  -838]
[ -196 -2663    40 -1501   837  1400 -1020 -2029]
[ 2698  1942 -1433  -874  2076  -324  3545 -1668]
[-1753  -276  2087  2294  -402   788  -831 -3557]
[ 2724   -46 -1526  2842  1379 -3581    78 -2328]
[ -339    94 -3524   120  3029 -1410 -3113  1877]
[-1021 -1550  1464  1331 -2608  -910  -933  -753]
[-2540  4203  -107  2743  4241   942  -643   186]
[-1038  -906   253  1668  1384 -2079  1385  1295]
[-4322  1039 -1240  -128   665   972 -2873 -1870]
[ 2224  -523  1371   -65   763 -1808 -2547   970]


 63%|██████▎   | 271/432 [00:02<00:01, 98.23it/s]

[  102  2031   596   -52 -1137  1606   390  2959]
[ -733  -122  2681 -1866  3353 -1000  -889 -1844]
[-2017  -559 -4105 -2993   563  2549  2056 -1826]
[-3912 -2415   -75 -4412  2026  -934  3391 -3836]
[ -466  -538  2791  -627   114   414  2334 -2988]
[  841 -1818 -1296  1996  3248 -1667  1590 -2253]
[-2715  1189 -2402  2734 -2030  -467 -3138  -368]
[1047 1249 4047 -658  625  130   11  456]
[   79   778  3599   775   124  1004  -211 -1749]
[-1763  2234  -428  -691 -2906  -752 -3569  3197]
[  366 -2774   730  -317  -211 -2981  -438 -2631]
[ 1799    13   293  -585  -832  4551  1185 -4338]
[ -750   396  -189  2298  2755 -4096 -4133 -1582]
[  787  1204   375  1460  3677 -1727   660  3112]
[ 3162 -1082  -159 -1137  -133  -876   902 -2216]
[ 2394 -2604 -1843  -631   857 -1024  -435  1483]
[ 3037 -2769   702  -243  -612   261  4668  4228]
[-2756  1118 -1985  -313 -2654  1476   549  -202]
[ 1934  1370   203  -421  -151   248  1215 -1900]
[ -291   880  -123  3195 -4403 -1422  -797  2057]
[ 1680  

 69%|██████▉   | 299/432 [00:02<00:01, 96.00it/s] 

[ 1535  2022  1708  1809  2517   -49 -2409  -332]
[ 2423   179  1363 -4051  1483 -1082 -3319   464]
[-1858  1800  -802 -4472   522 -1975  3277 -2667]
[ -503 -3392  -235  -924   538  3441  1529  -433]
[ 2943 -4940   411   821  -953  1069   173   447]
[-1378 -1852 -1855  1781 -1681  -503  2351  -203]
[ 865  -12 3541  932  325  945  364 1580]
[-1101 -2237   682 -2744  2756 -1406  2513  4268]
[-3271  3303 -3754  1040  1431 -2488  1570 -2391]
[ -280  1501 -3068    39  2581 -1715 -3270  -769]
[-4187  1379  -499  3821  2497 -2152   328  -781]
[-2559  2422 -1410  2389 -1357   161   288  2315]
[-3824  2360 -3471 -4477 -2547   603 -1684  2542]
[2093  790  982 2632  798 -273  430 2382]
[ 3266 -1066 -4011  2122 -2385  3041 -1977   -18]
[  359 -1477   324   221  -484  1168  -819  -814]
[-4036  1744 -1267  -883   701  3044  -844 -1349]
[-1297 -3829 -1997   -53  2183  2748  -426 -1320]
[ 1366 -1251 -1897 -1564 -1214  -802 -2776   770]


 72%|███████▏  | 313/432 [00:02<00:01, 106.01it/s]

[  752 -2167  1037  4535  -218  -344  2733 -1897]
[-2794  -324  2016 -2504  2652   163  1728   877]
[  947 -1698   276 -3027  3383 -1542 -1175 -1230]
[-3716 -2131 -1303  -291 -1248  1397  -491   358]
[-2644 -2696 -2899  -364 -1189  1996 -1843  3101]
[ 1887  3133  2578  4845  -809  1486 -1121  2801]
[ -671  1343  1103 -2328 -3602  3244  -159 -1628]
[ 1111 -3140   612  -238   143   878  2759  1147]
[-2005  1938  1804  -877 -1139   489  2559  1578]
[-1314  2098   210  -249  -468  3142    97   676]
[ 1901 -1069  3453  1999  -367  1341 -3446  -564]
[ 2878   197   -44  -651  1960  3036  -675 -2521]
[-1863  -225 -1360   750 -1728 -2157  -953  1818]
[ 1610 -2284    97  -605  1967  2971 -2332 -1464]
[ 1590 -4858  1008  1024  3425  1589  2969  2486]
[ 1161 -2257 -2616  -210  2651 -2361   154  1343]
[ -445  1991  2507   256 -1752 -2807 -1924 -2835]
[ 1288 -2019  1217   -77 -2092 -2046 -1381   749]
[ 3808 -4422 -1433 -2543 -2455   183    94 -1785]
[  -60  1692  2404  1892 -2995  -290  1981 -2617]


 80%|███████▉  | 344/432 [00:03<00:00, 104.20it/s]

[ 2856 -3672  1987  1707  -241   464  3226  3964]
[ 2085 -1362  3454 -2176 -2509  -160 -2876  2571]
[ 1587  1915  4017 -1908 -2402 -4260  4004  -390]
[  399  2757  -311  1567 -3365  -143  2881 -3748]
[  422   119  1625  1390  -139 -1751  -357  3910]
[ 1947  4176   561   526 -1914 -2170   880    86]
[ 2038  -451  2095  1795   609  -558 -2676 -2610]
[-2442   650   417   129 -1546  -545  2850   610]
[ 2246   -97  3517   708 -2802  3184  1612 -2156]
[-1694   393 -2134 -2851 -2750  -961 -3259    10]
[ 2459 -2826   205 -1692  -830  2361  -883  -524]
[-1258  4558  -140 -1422 -3239  1494 -1506 -1876]
[-3069 -3868  -694  4686 -1076 -2201   196   466]
[ -469  1577   430   709 -2092 -3386 -1762 -2759]
[  977 -2914   616  -757   622  1341  1961   464]
[-1222   -14  2233   -93 -1154 -1277   152  -902]
[ 2011 -2852 -2285 -1021  1601 -4089 -1010  -400]
[ 1922 -1823 -2383 -1925  4075 -3459  1948   601]
[-1955 -2255 -3793   130  -590 -1470 -1280   306]
[-1050  4022    21  -496  -102 -1579   426  1502]


 83%|████████▎ | 360/432 [00:03<00:00, 104.34it/s]

[ -138 -3999   907   519    94  1784  1793 -4019]
[-2772 -2450 -1846   180  1617 -3855 -2665  -457]
[ -673 -1549  3704 -1405  -489 -3676  2224   427]
[ 2963    52  -148   734 -1495 -1969   614 -3829]
[  964   269  1959 -2706 -1822  1624   -30  -905]
[ -497   558  -492  3072  -829 -1234  -753 -2110]
[ 1824   901 -1440  1482 -1676  -856    53  1865]
[ -357 -3138  3814  1978 -1087  1509  2183 -1478]
[ -159 -1200  -721  1589  3738   241  2337 -2233]
[ 2171   828  3014  2588 -1839  2702  1004  1788]
[  247 -2691  1410  1955  2160  -686   533  -324]
[1625 3628 1932  522 2594   48 3893 4167]
[-1041  -667  -150 -1188   162 -2249  2055  3971]
[-1680  2592 -3459 -1651  3575  1851   516 -2589]
[ -530 -2160 -1008 -3608  3481   549 -1634 -1497]
[ 2505  3278  1234  -525  2300 -3032  -219 -1233]
[ 1568   386 -2814  1667  -409 -1936  1671  -611]
[ -906  1974 -2899  2788  2709 -3998 -3716  -563]
[ 1180 -1024 -3067  -413 -1018 -3457  4114 -2147]


 89%|████████▉ | 386/432 [00:03<00:00, 101.17it/s]

[  390  1662 -1350  -693 -2175 -1002   474   741]
[ 1231 -1553   986  2374  2336  3634   408  2539]
[-3741  2595 -3636  3885  1990   835  1703  -358]
[  -31  -276 -1733 -2007 -1801  -560 -2716   450]
[  388 -1996   407   350 -1426  1604 -3249 -2191]
[-1822  -435   168 -2514 -1570 -2643  -538  -927]
[-1317  -743   699  1489  1331   562  -492  2935]
[  144   374  3961  1052    69 -3671   -51  2961]
[   40  2965  -938  -752   783  3154 -2176 -2063]
[ 1054   474  1117 -3324  1253 -1812  1513  -525]
[ 3872  1258  3710  1739  1655 -1873   249   243]
[  759   498  2389  -139  3963  1773 -2549  1211]
[ -233 -2818 -1771 -2222  1747  1861    36  -956]
[ 4014 -3395   -21 -4242    86 -4152  -327  1660]
[-3030 -1076   702  -940 -3491  1855 -2432  1096]
[ -731 -1228  2348  -681 -1074 -1392  3524   226]
[ 4253  -781  1983  1526  -998   216   138 -1249]
[-1578 -2674 -2102  3337   573  1489  1416  2729]
[-1165  3865   342   189 -1280 -3590  -394 -2642]
[-1522 -2162  1189 -2164  -877   943  3340  -591]


 97%|█████████▋| 417/432 [00:03<00:00, 109.53it/s]

[-1399  3010  -943  4767  1174  4038 -2362 -2758]
[-1114   143   978 -1129   550  1985  2798   650]
[-3895  1831   576  -405 -3417  3127  -380 -2067]
[ 2454  1260  2932  4668   120   183 -1946  -203]
[ 1055 -3692 -1232   141  -882  3576 -3002 -1491]
[-1126  3168  1636  1130  2952  1796  2257 -1441]
[ -773 -2030   403  1575 -1737  3687 -1292 -1198]
[3439  714 2794 4527 2805  -30 1778 -198]
[ -756 -1292 -1360   771  1901  2552   530  -391]
[ -407  1091   381 -1558   905 -1676   470  2019]
[ 2668   617  -229  2853  3183  1401 -2345   515]
[-2507 -2552   206 -1075 -1285  -541  -198 -1056]
[-1987  1165  3248  -654  3610 -1078   278   596]
[ 2612  -498  3495  -579 -1894 -4861   127 -3171]
[ 1277  2063   804  2279  -991 -1793  -917 -1532]
[ 3824 -4379  -560  -163   538 -1700   302   971]
[ -679  4417    80 -2646 -4135   267  -896 -3222]
[  141  3226  3356 -1199  3858  1142  2303  3485]
[ 2880 -2232  -962  1873   952  1431 -2982 -2344]
[-3536 -1224  3391  -240  2609  1627 -2167  2847]
[ 2584  

100%|██████████| 432/432 [00:04<00:00, 104.79it/s]

[  279 -3491 -2236  -997  1208 -3487 -3491  3649]
[-1254 -3001  3129 -3660   -85 -2049 -1014 -1540]
[  522   148 -2878 -4224   310 -1985 -1188  1066]
[ 106  353 3884 1541 1707 1951  300  145]
[ 1458 -2214  2309 -4338 -3093  -107  4273  1546]
[ 3902 -3972   172 -2733 -1865   291  1653   141]
[2264 1201 2701  888 1784 1196 1541  707]
[-1437 -2711 -1571  2414 -2202  1738 -2713 -2573]
[ -278   504  3826 -3030  -510  2617  1389    79]
[ 2957 -2680   -27  1438 -2312  -634   768 -2582]
[-3380 -2694 -2164  -371  3345 -3053   217  3043]
[ 3102   146  3920 -3700 -1321  1017 -1061 -1355]
[ 2459  1254 -2554  1168  -422 -3159  3595 -1725]
[-3779 -3283 -3212  -916  2705  3506  -326  3010]
[-91]


In [20]:
import numpy as np

In [42]:
for i,  in enumerate(zip(train_loader,cycle(val_loader))):
    txt, segment, mask, img, img_aug, tgt, img_id= batch[0]
    txt, segment, mask, img, img_aug, tgt, img_id= batch[0]
    print(img_id)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [2]:
from datasets import load_dataset

In [3]:
dataset = load_dataset('oscar', 'unshuffled_deduplicated_it')

Reusing dataset oscar (/002/usuarios/ivonne.monter/.cache/huggingface/datasets/oscar/unshuffled_deduplicated_it/1.0.0/84838bd49d2295f62008383b05620571535451d84545037bb94d6f3501651df2)


  0%|          | 0/1 [00:00<?, ?it/s]

In [4]:
dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'text'],
        num_rows: 28522082
    })
})

In [ ]:
from tqdm.auto import tqdm

text_data = []
file_count = 0

for sample in tqdm(dataset['train']):
    sample = sample['text'].replace('\n', '')
    text_data.append(sample)
    if len(text_data) == 10_000:
        # once we git the 10K mark, save to file
        with open(f'dataset/text_{file_count}.txt', 'w', encoding='utf-8') as fp:
            fp.write('\n'.join(text_data))
        text_data = []
        file_count += 1
# after saving in 10K chunks, we will have ~2082 leftover samples, we save those now too
with open(f'dataset/text_{file_count}.txt', 'w', encoding='utf-8') as fp:
    fp.write('\n'.join(text_data))

  0%|          | 0/28522082 [00:00<?, ?it/s]